@host = http://localhost
@port = :8080
@api = {{host}}{{port}}
@id = 65fc53a8a8c6f1a26c007414

### Create a new user
POST {{api}}/users
Content-Type: application/json

{
    "name": "frani",
    "lastname": "frani",
    "email": "frani@mail.co",
    "password": "qwerty123456789",
    "username": "frani"
}

### Get all users
GET {{api}}/users

### Get a user
GET {{api}}/users/{{id}}

### Update a user
PATCH {{api}}/users/{{id}}
Content-Type: application/json

{
    "name": "asdfasdfasd"
}

### Delete a user
DELETE {{api}}/users/{{id}}
